# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.13.0
pipelines:
   branches:
      master:
        - step:
           deployment: production
           caches:
           - node
           script:
            - npm install
            - npm install -g @angular/cli
            - npm install -g firebase-tools
            - ng build --prod
            - firebase deploy --token=$FIREBASE_TOKEN --project tabletenis-b5307 --non-interactive
